# Site settings
title: 役物工坊
email: njin.cool@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  hello world!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: njin
github_username:  sqrtqiezi

# Build settings
markdown: kramdown
